# Generated by Django 4.0.4 on 2022-04-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('Song_ID', models.AutoField(db_column='Course_ID', primary_key=True, serialize=False, verbose_name='Course_ID')),
                ('Song_Name', models.CharField(db_column='Course_Name', max_length=255, unique=True, verbose_name='Course_name')),
                ('Language', models.CharField(db_column='Language', max_length=255, verbose_name='Language')),
                ('Singer', models.CharField(db_column='Singer', max_length=255, verbose_name='Singer')),
                ('Initial', models.SmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F'), (7, 'G'), (8, 'H'), (9, 'I'), (10, 'J'), (11, 'K'), (12, 'L'), (13, 'M'), (14, 'N'), (15, 'O'), (16, 'P'), (17, 'Q'), (18, 'R'), (19, 'S'), (20, 'T'), (21, 'U'), (22, 'V'), (23, 'W'), (24, 'X'), (25, 'Y'), (26, 'Z')], db_column='Initial', null=True, verbose_name='Initial')),
                ('Remark', models.CharField(db_column='Remark', max_length=255, null=True, verbose_name='Remark')),
            ],
            options={
                'db_table': 'Songs',
            },
        ),
    ]
