# Generated by Django 4.0.4 on 2022-04-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='Song_ID',
            field=models.AutoField(db_column='Song_ID', primary_key=True, serialize=False, verbose_name='Song_ID'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='Song_Name',
            field=models.CharField(db_column='Song_Name', max_length=255, unique=True, verbose_name='Song_name'),
        ),
    ]
