# Generated by Django 4.0.4 on 2022-04-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_songs_song_id_alter_songs_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='Remark',
            field=models.CharField(blank=True, db_column='Remark', max_length=255, null=True, verbose_name='Remark'),
        ),
    ]
